### ISSUE TITLE
Can't draw options route correctly by PathExtractor

### ISSUE THREAD

**Issue by frokaikan** [gotham-rs/gotham#288] opened 2018-11-09 17:03 UTC
My server needs to support CORS, so I write the following code:
```
#[derive(Clone, NewMiddleware)]
pub struct CORSMiddle;

impl Middleware for CORSMiddle
{
    fn call<Chain>(self, s : State, chain : Chain) -> Box<HandlerFuture>
    where
        Chain : FnOnce(State) -> Box<HandlerFuture>,
    {
        let f = chain(s).and_then( move |(s, mut res)|
        {
            {
                let headers = res.headers_mut();
                headers.insert("Access-Control-Allow-Origin", "*".parse().unwrap());
                headers.insert("Access-Control-Allow-Methods", "POST, OPTIONS".parse().unwrap());
                headers.insert("Access-Control-Allow-Headers", "Content-Type, X-token, X-op, X-cnt, X-logx".parse().unwrap());
            }
            future::ok((s, res))
        });
        Box::new(f)
    }
}

#[derive(Deserialize, Serialize, StateData, StaticResponseExtender)]
pub struct CORSHelper 
{
    #[serde(rename = "*")]
    xapi : Vec<String>,
}

pub fn CORS(s : State) -> Box<HandlerFuture>
{
    // let _t = CORSHelper::borrow_from(&s);
    let res = create_empty_response(&s, StatusCode::OK);
    Box::new(future::ok((s, res)))
}

pub fn router() -> Router {
    let CHKMiddle = StateMiddleware::new(checker::new());
    let SEEDMiddle = StateMiddleware::new(seeder::new());
    let LOGMiddle = StateMiddleware::new(logger::new());
    let (chain, pipelines) = single_pipeline(new_pipeline().add(CORSMiddle).add(CHKMiddle).add(SEEDMiddle)/*.add(LOGMiddle)*/.build());
    build_router(chain, pipelines, |route| {
        route.options("/api/*").with_path_extractor::<CORSHelper>().to(CORS);
    })
}

fn main() {
    let addr = "127.0.0.1:8080";
    gotham::start(addr, upper_api::router());
}


```
But when I want to send an options to 127.0.0.1:8080/api/xx, I got a 405 : method not allowed.
Is there anywhere I wrote wrong?

**Comment by colinbankier** [comment] 2018-11-12 00:07
Hi @frokaikan , thanks for reaching out :)
I took a look at your example above, and with commenting out references to code not supplied, and one minor adjustment, it seems to work fine for me. (on gotham 0.3)
I see you're calling `upper_api::router()` in `main()`, instead of just `router()` - maybe you're accidentally using a router from a different module than you intended? (it's not clear what else is in your project from the snippet).
By fixing this, and removing your use of SEEDMiddle and CHKMiddle (as not supplied) - it worked:
```
curl -XOPTIONS 127.0.0.1:8080/api/xx -v          master
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> OPTIONS /api/xx HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.62.0
> Accept: */*
>
< HTTP/1.1 200 OK
< x-request-id: 5c75d4b5-dc8f-43ad-912f-34ec3f536bb0
< access-control-allow-origin: *
< access-control-allow-methods: POST, OPTIONS
< access-control-allow-headers: Content-Type, X-token, X-op, X-cnt, X-logx
< content-length: 0
< date: Sun, 11 Nov 2018 23:54:32 GMT
<
* Connection #0 to host 127.0.0.1 left intact
```

If it's not this - something in these other middlewares must be rejecting the request. Hopefully that helps you track down the issue :)

**Comment by frokaikan** [comment] 2018-11-12 02:36
Ah, sorry but I don't make my problem clear...
there is also a POST router for /api/xx, such as this:
```

#[derive(Clone, NewMiddleware)]
pub struct CORSMiddle;

impl Middleware for CORSMiddle
{
    fn call<Chain>(self, s : State, chain : Chain) -> Box<HandlerFuture>
    where
        Chain : FnOnce(State) -> Box<HandlerFuture>,
    {
        let f = chain(s).and_then( move |(s, mut res)|
        {
            {
                let headers = res.headers_mut();
                headers.insert("Access-Control-Allow-Origin", "*".parse().unwrap());
                headers.insert("Access-Control-Allow-Methods", "POST, OPTIONS".parse().unwrap());
                headers.insert("Access-Control-Allow-Headers", "Content-Type, X-token, X-op, X-cnt, X-logx".parse().unwrap());
            }
            future::ok((s, res))
        });
        Box::new(f)
    }
}

#[derive(Deserialize, Serialize, StateData, StaticResponseExtender)]
pub struct CORSHelper 
{
    #[serde(rename = "*")]
    xapi : Vec<String>,
}

pub fn CORS(s : State) -> Box<HandlerFuture>
{
    // let _t = CORSHelper::borrow_from(&s);
    let res = create_empty_response(&s, StatusCode::OK);
    Box::new(future::ok((s, res)))
}

pub fn postit(s : State) -> Box<HandlerFuture>
{
    // let _t = CORSHelper::borrow_from(&s);
    let res = create_empty_response(&s, StatusCode::OK);
    Box::new(future::ok((s, res)))
}

pub fn router() -> Router {
    let (chain, pipelines) = single_pipeline(new_pipeline().add(CORSMiddle).build());
    build_router(chain, pipelines, |route| {
        route.options("/api/*").with_path_extractor::<CORSHelper>().to(CORS);
        route.post("/api/xx").to(postit);
    })
}

fn main() {
    let addr = "127.0.0.1:8080";
    gotham::start(addr, router());
}
```

Then when I send an OPTIONS to /api/xx, I got a 405 - Method Not Allowed.

**Comment by sezna** [comment] 2020-09-02 17:21
I'm going to close this for now, as a duplicate of #119 since a fix there would give you a fix here.

**Closed by sezna** 2020-09-02 17:21 UTC
