### ISSUE TITLE
How can I make run middleware if there is no matches in router?

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [gotham-rs/gotham#375] opened 2019-11-19 21:31 UTC
I recently started a project and I added special middleware to render special pages for 404 and 500 results.
But the issue is that it not run sometimes.

How can I make my middleware trigger if no matching routes in router?

I created very small example program to show the issue:

```rust
extern crate gotham;
#[macro_use]
extern crate gotham_derive;
extern crate hyper;
extern crate mime;

use gotham::router::builder::DefineSingleRoute;
use gotham::router::builder::DrawRoutes;

use gotham::middleware::Middleware;
use gotham::router::Router;
use gotham::pipeline::set::new_pipeline_set;
use gotham::pipeline::new_pipeline;
use gotham::pipeline::set::finalize_pipeline_set;
use gotham::router::builder::build_router;
use gotham::state::State;
use gotham::handler::HandlerFuture;


const HELLO_WORLD: &str = "Hello World!";
const HELLO_MIDDLE: &str = "Hello World From Middle!";

pub fn say_hello(state: State) -> (State, &'static str) {
    (state, HELLO_WORLD)
}

#[derive(Clone, NewMiddleware)]
pub struct PrintMiddleWare;

impl Middleware for PrintMiddleWare {
    fn call<Chain>(self, state: State, chain: Chain) -> Box<HandlerFuture>
    where
        Chain: FnOnce(State) -> Box<HandlerFuture>,
    {
    	println!("{:?}", HELLO_MIDDLE);
    	chain(state)
    }
}

fn router()->Router{
	let pipelines = new_pipeline_set();
    let (pipelines, default) = pipelines.add(
        new_pipeline()
            .add(PrintMiddleWare{})
            .build(),
    );
    let pipeline_set = finalize_pipeline_set(pipelines);
    let default_chain = (default, ());
    build_router(default_chain, pipeline_set, |route| {
    	// Here will print
    	route.get_or_head("/").to(say_hello);
    	// Here will print
    	route.get_or_head("/will-print").to(say_hello);
    	// Will NOT print on /test because no matches
    	// But I want to print
    })
}

pub fn main() {
    let addr = "127.0.0.1:7878";
    println!("Listening for requests at http://{}", addr);
    gotham::start(addr, router())
}

```

**Comment by AngelicosPhosphoros** [comment] 2019-11-20 18:10
I handled it by adding this at the end of routes:

route.get_or_head("/*").to(|state|{
    let response = create_empty_response(&state, StatusCode::NOT_FOUND);
    (state, response)
});

**Comment by colinbankier** [comment] 2019-11-21 05:12
Thanks for the report @AngelicosPhosphoros . There have been a few similar issues such as #256 or #292. These are definitely things we'd like to address as we improve the router.

**Comment by msrd0** [comment] 2020-08-26 14:36
Closing as duplicate of #256

**Closed by msrd0** 2020-08-26 14:36 UTC
