### ISSUE TITLE
Unix Domain?

### ISSUE THREAD

**Issue by cheako** [gotham-rs/gotham#386] opened 2019-12-30 19:47 UTC
Handling requests from an upstream server, or tor, is a must! If the upstream server is local it becomes encumbering to use ports on a localhost interface for IPC. Enter Unix Domain Sockets.

**Comment by msrd0** [comment] 2021-03-01 22:35
This seems to be a duplicate of #183

**Closed by msrd0** 2021-03-01 22:35 UTC
Labels: feature, help wanted

**Comment by cheako** [comment] 2021-03-02 12:05
I fundamentally disagree with combining a bug about the Session layer with another about Transport.

https://github.com/gotham-rs/gotham/issues/183#issuecomment-788344645 I don't see why optional, but rather different https://doc.rust-lang.org/std/os/unix/net/struct.UnixStream.html#method.peer_addr

I'm happy to work on a PR that replaces every instance of std::net::SocketAddr with a new enum that, under feature `unix-sockets`, has a third entry `UNIX<std::os::unix::net::SocketAddr>`.

**Comment by msrd0** [comment] 2021-03-02 13:19
#183 allows you to choose whatever transport you want to use and put gotham on top of it. This can be a unix domain socket, whatever windows uses instead of that, a QUIC stream, or whatever other transportation you require. Hence gotham has no way of knowing what type of socket address you are using, so it should be made optional, and not conditionally have a unix variant.

**Comment by nyarly** [comment] 2021-04-12 16:57
Agreeing with @msrd0 here: it looks a lot like the transport layer involvement in Gotham comes down to logging. But again, 3rd party middleware might care.

Use cases worth investigating here are session hijacking e.g. for websockets.

I think it may also be that there's Gotham-the-server and Gotham-the-app-container, and that there might need to be something at the interface with regards to the transport.

If there's no other use of the transport though, I'd say we should likely transition to a client identifier (maybe a newtype around String) for logging purposes.
